version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./HotelWiseWeb:/HotelWiseWeb
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/HotelWiseWeb/key.json
      - DEBUG=1
