version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:464.0.0
    volumes:
      - gcp-creds:/creds
      - .:/HotelWiseWeb
    working_dir: /HotelWiseWeb
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds:
